//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.ZxccxzxczxcxzXXX
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Ед изм.
    /// </summary>
    // *** Start programmer edit section *** (ЕдИзм CustomAttributes)

    // *** End programmer edit section *** (ЕдИзм CustomAttributes)
    public enum ЕдИзм
    {
        
        // *** Start programmer edit section *** (ЕдИзм.Мбайт CustomAttributes)

        // *** End programmer edit section *** (ЕдИзм.Мбайт CustomAttributes)
        Мбайт,
        
        // *** Start programmer edit section *** (ЕдИзм.Гбайт CustomAttributes)

        // *** End programmer edit section *** (ЕдИзм.Гбайт CustomAttributes)
        Гбайт,
        
        // *** Start programmer edit section *** (ЕдИзм.Тбайт CustomAttributes)

        // *** End programmer edit section *** (ЕдИзм.Тбайт CustomAttributes)
        Тбайт,
        
        // *** Start programmer edit section *** (ЕдИзм.Пбайт CustomAttributes)

        // *** End programmer edit section *** (ЕдИзм.Пбайт CustomAttributes)
        Пбайт,
    }
}
