//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.ZxccxzxczxcxzXXX
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Программы.
    /// </summary>
    // *** Start programmer edit section *** (Программы CustomAttributes)

    // *** End programmer edit section *** (Программы CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПрограммыE", new string[] {
            "Название as \'Название\'",
            "Описание as \'Описание\'",
            "Версия as \'Версия\'",
            "Размер as \'Размер\'",
            "ЕдИзмерения as \'Ед измерения\'"})]
    public class Программы : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание;
        
        private string fОписание;
        
        private string fВерсия;
        
        private string fРазмер;
        
        private IIS.ZxccxzxczxcxzXXX.ЕдИзм fЕдИзмерения;
        
        private IIS.ZxccxzxczxcxzXXX.Сервер fСервер;
        
        // *** Start programmer edit section *** (Программы CustomMembers)

        // *** End programmer edit section *** (Программы CustomMembers)

        
        /// <summary>
        /// Версия.
        /// </summary>
        // *** Start programmer edit section *** (Программы.Версия CustomAttributes)

        // *** End programmer edit section *** (Программы.Версия CustomAttributes)
        [StrLen(255)]
        public virtual string Версия
        {
            get
            {
                // *** Start programmer edit section *** (Программы.Версия Get start)

                // *** End programmer edit section *** (Программы.Версия Get start)
                string result = this.fВерсия;
                // *** Start programmer edit section *** (Программы.Версия Get end)

                // *** End programmer edit section *** (Программы.Версия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Программы.Версия Set start)

                // *** End programmer edit section *** (Программы.Версия Set start)
                this.fВерсия = value;
                // *** Start programmer edit section *** (Программы.Версия Set end)

                // *** End programmer edit section *** (Программы.Версия Set end)
            }
        }
        
        /// <summary>
        /// ЕдИзмерения.
        /// </summary>
        // *** Start programmer edit section *** (Программы.ЕдИзмерения CustomAttributes)

        // *** End programmer edit section *** (Программы.ЕдИзмерения CustomAttributes)
        public virtual IIS.ZxccxzxczxcxzXXX.ЕдИзм ЕдИзмерения
        {
            get
            {
                // *** Start programmer edit section *** (Программы.ЕдИзмерения Get start)

                // *** End programmer edit section *** (Программы.ЕдИзмерения Get start)
                IIS.ZxccxzxczxcxzXXX.ЕдИзм result = this.fЕдИзмерения;
                // *** Start programmer edit section *** (Программы.ЕдИзмерения Get end)

                // *** End programmer edit section *** (Программы.ЕдИзмерения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Программы.ЕдИзмерения Set start)

                // *** End programmer edit section *** (Программы.ЕдИзмерения Set start)
                this.fЕдИзмерения = value;
                // *** Start programmer edit section *** (Программы.ЕдИзмерения Set end)

                // *** End programmer edit section *** (Программы.ЕдИзмерения Set end)
            }
        }
        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Программы.Название CustomAttributes)

        // *** End programmer edit section *** (Программы.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Программы.Название Get start)

                // *** End programmer edit section *** (Программы.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Программы.Название Get end)

                // *** End programmer edit section *** (Программы.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Программы.Название Set start)

                // *** End programmer edit section *** (Программы.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Программы.Название Set end)

                // *** End programmer edit section *** (Программы.Название Set end)
            }
        }
        
        /// <summary>
        /// Описание.
        /// </summary>
        // *** Start programmer edit section *** (Программы.Описание CustomAttributes)

        // *** End programmer edit section *** (Программы.Описание CustomAttributes)
        [StrLen(255)]
        public virtual string Описание
        {
            get
            {
                // *** Start programmer edit section *** (Программы.Описание Get start)

                // *** End programmer edit section *** (Программы.Описание Get start)
                string result = this.fОписание;
                // *** Start programmer edit section *** (Программы.Описание Get end)

                // *** End programmer edit section *** (Программы.Описание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Программы.Описание Set start)

                // *** End programmer edit section *** (Программы.Описание Set start)
                this.fОписание = value;
                // *** Start programmer edit section *** (Программы.Описание Set end)

                // *** End programmer edit section *** (Программы.Описание Set end)
            }
        }
        
        /// <summary>
        /// Размер.
        /// </summary>
        // *** Start programmer edit section *** (Программы.Размер CustomAttributes)

        // *** End programmer edit section *** (Программы.Размер CustomAttributes)
        [StrLen(255)]
        public virtual string Размер
        {
            get
            {
                // *** Start programmer edit section *** (Программы.Размер Get start)

                // *** End programmer edit section *** (Программы.Размер Get start)
                string result = this.fРазмер;
                // *** Start programmer edit section *** (Программы.Размер Get end)

                // *** End programmer edit section *** (Программы.Размер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Программы.Размер Set start)

                // *** End programmer edit section *** (Программы.Размер Set start)
                this.fРазмер = value;
                // *** Start programmer edit section *** (Программы.Размер Set end)

                // *** End programmer edit section *** (Программы.Размер Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.ZxccxzxczxcxzXXX.Сервер.
        /// </summary>
        // *** Start programmer edit section *** (Программы.Сервер CustomAttributes)

        // *** End programmer edit section *** (Программы.Сервер CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Сервер"})]
        public virtual IIS.ZxccxzxczxcxzXXX.Сервер Сервер
        {
            get
            {
                // *** Start programmer edit section *** (Программы.Сервер Get start)

                // *** End programmer edit section *** (Программы.Сервер Get start)
                IIS.ZxccxzxczxcxzXXX.Сервер result = this.fСервер;
                // *** Start programmer edit section *** (Программы.Сервер Get end)

                // *** End programmer edit section *** (Программы.Сервер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Программы.Сервер Set start)

                // *** End programmer edit section *** (Программы.Сервер Set start)
                this.fСервер = value;
                // *** Start programmer edit section *** (Программы.Сервер Set end)

                // *** End programmer edit section *** (Программы.Сервер Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПрограммыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПрограммыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПрограммыE", typeof(IIS.ZxccxzxczxcxzXXX.Программы));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Программы.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfПрограммы CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfПрограммы CustomAttributes)
    public class DetailArrayOfПрограммы : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.ZxccxzxczxcxzXXX.DetailArrayOfПрограммы members)

        // *** End programmer edit section *** (IIS.ZxccxzxczxcxzXXX.DetailArrayOfПрограммы members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Программы by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Программы.
        /// </summary>
        public DetailArrayOfПрограммы(IIS.ZxccxzxczxcxzXXX.Сервер fСервер) : 
                base(typeof(Программы), ((ICSSoft.STORMNET.DataObject)(fСервер)))
        {
        }
        
        public IIS.ZxccxzxczxcxzXXX.Программы this[int index]
        {
            get
            {
                return ((IIS.ZxccxzxczxcxzXXX.Программы)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.ZxccxzxczxcxzXXX.Программы dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
