//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.ZxccxzxczxcxzXXX
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сервер.
    /// </summary>
    // *** Start programmer edit section *** (Сервер CustomAttributes)

    // *** End programmer edit section *** (Сервер CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СерверE", new string[] {
            "Протокол as \'Протокол\'",
            "IP as \'IP\'",
            "Порт as \'Порт\'",
            "Сотрудник as \'Сотрудник\'",
            "Сотрудник.Имя as \'Имя\'"}, Hidden=new string[] {
            "Сотрудник.Имя"})]
    [AssociatedDetailViewAttribute("СерверE", "Настройки", "НастройкиE", true, "", "Настройки", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("СерверE", "Программы", "ПрограммыE", true, "", "Программы", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("СерверE", "Сотрудник", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Имя")]
    [View("СерверL", new string[] {
            "Протокол as \'Протокол\'",
            "IP as \'IP\'",
            "Порт as \'Порт\'",
            "Сотрудник.Имя as \'Имя\'"})]
    public class Сервер : ICSSoft.STORMNET.DataObject
    {
        
        private string fПротокол;
        
        private string fIP;
        
        private int fПорт;
        
        private IIS.ZxccxzxczxcxzXXX.Сотрудник fСотрудник;
        
        private IIS.ZxccxzxczxcxzXXX.DetailArrayOfНастройки fНастройки;
        
        private IIS.ZxccxzxczxcxzXXX.DetailArrayOfПрограммы fПрограммы;
        
        // *** Start programmer edit section *** (Сервер CustomMembers)

        // *** End programmer edit section *** (Сервер CustomMembers)

        
        /// <summary>
        /// IP.
        /// </summary>
        // *** Start programmer edit section *** (Сервер.IP CustomAttributes)

        // *** End programmer edit section *** (Сервер.IP CustomAttributes)
        [StrLen(255)]
        public virtual string IP
        {
            get
            {
                // *** Start programmer edit section *** (Сервер.IP Get start)

                // *** End programmer edit section *** (Сервер.IP Get start)
                string result = this.fIP;
                // *** Start programmer edit section *** (Сервер.IP Get end)

                // *** End programmer edit section *** (Сервер.IP Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сервер.IP Set start)

                // *** End programmer edit section *** (Сервер.IP Set start)
                this.fIP = value;
                // *** Start programmer edit section *** (Сервер.IP Set end)

                // *** End programmer edit section *** (Сервер.IP Set end)
            }
        }
        
        /// <summary>
        /// Порт.
        /// </summary>
        // *** Start programmer edit section *** (Сервер.Порт CustomAttributes)

        // *** End programmer edit section *** (Сервер.Порт CustomAttributes)
        public virtual int Порт
        {
            get
            {
                // *** Start programmer edit section *** (Сервер.Порт Get start)

                // *** End programmer edit section *** (Сервер.Порт Get start)
                int result = this.fПорт;
                // *** Start programmer edit section *** (Сервер.Порт Get end)

                // *** End programmer edit section *** (Сервер.Порт Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сервер.Порт Set start)

                // *** End programmer edit section *** (Сервер.Порт Set start)
                this.fПорт = value;
                // *** Start programmer edit section *** (Сервер.Порт Set end)

                // *** End programmer edit section *** (Сервер.Порт Set end)
            }
        }
        
        /// <summary>
        /// Протокол.
        /// </summary>
        // *** Start programmer edit section *** (Сервер.Протокол CustomAttributes)

        // *** End programmer edit section *** (Сервер.Протокол CustomAttributes)
        [StrLen(255)]
        public virtual string Протокол
        {
            get
            {
                // *** Start programmer edit section *** (Сервер.Протокол Get start)

                // *** End programmer edit section *** (Сервер.Протокол Get start)
                string result = this.fПротокол;
                // *** Start programmer edit section *** (Сервер.Протокол Get end)

                // *** End programmer edit section *** (Сервер.Протокол Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сервер.Протокол Set start)

                // *** End programmer edit section *** (Сервер.Протокол Set start)
                this.fПротокол = value;
                // *** Start programmer edit section *** (Сервер.Протокол Set end)

                // *** End programmer edit section *** (Сервер.Протокол Set end)
            }
        }
        
        /// <summary>
        /// Сервер.
        /// </summary>
        // *** Start programmer edit section *** (Сервер.Сотрудник CustomAttributes)

        // *** End programmer edit section *** (Сервер.Сотрудник CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудник"})]
        [NotNull()]
        public virtual IIS.ZxccxzxczxcxzXXX.Сотрудник Сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (Сервер.Сотрудник Get start)

                // *** End programmer edit section *** (Сервер.Сотрудник Get start)
                IIS.ZxccxzxczxcxzXXX.Сотрудник result = this.fСотрудник;
                // *** Start programmer edit section *** (Сервер.Сотрудник Get end)

                // *** End programmer edit section *** (Сервер.Сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сервер.Сотрудник Set start)

                // *** End programmer edit section *** (Сервер.Сотрудник Set start)
                this.fСотрудник = value;
                // *** Start programmer edit section *** (Сервер.Сотрудник Set end)

                // *** End programmer edit section *** (Сервер.Сотрудник Set end)
            }
        }
        
        /// <summary>
        /// Сервер.
        /// </summary>
        // *** Start programmer edit section *** (Сервер.Настройки CustomAttributes)

        // *** End programmer edit section *** (Сервер.Настройки CustomAttributes)
        public virtual IIS.ZxccxzxczxcxzXXX.DetailArrayOfНастройки Настройки
        {
            get
            {
                // *** Start programmer edit section *** (Сервер.Настройки Get start)

                // *** End programmer edit section *** (Сервер.Настройки Get start)
                if ((this.fНастройки == null))
                {
                    this.fНастройки = new IIS.ZxccxzxczxcxzXXX.DetailArrayOfНастройки(this);
                }
                IIS.ZxccxzxczxcxzXXX.DetailArrayOfНастройки result = this.fНастройки;
                // *** Start programmer edit section *** (Сервер.Настройки Get end)

                // *** End programmer edit section *** (Сервер.Настройки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сервер.Настройки Set start)

                // *** End programmer edit section *** (Сервер.Настройки Set start)
                this.fНастройки = value;
                // *** Start programmer edit section *** (Сервер.Настройки Set end)

                // *** End programmer edit section *** (Сервер.Настройки Set end)
            }
        }
        
        /// <summary>
        /// Сервер.
        /// </summary>
        // *** Start programmer edit section *** (Сервер.Программы CustomAttributes)

        // *** End programmer edit section *** (Сервер.Программы CustomAttributes)
        public virtual IIS.ZxccxzxczxcxzXXX.DetailArrayOfПрограммы Программы
        {
            get
            {
                // *** Start programmer edit section *** (Сервер.Программы Get start)

                // *** End programmer edit section *** (Сервер.Программы Get start)
                if ((this.fПрограммы == null))
                {
                    this.fПрограммы = new IIS.ZxccxzxczxcxzXXX.DetailArrayOfПрограммы(this);
                }
                IIS.ZxccxzxczxcxzXXX.DetailArrayOfПрограммы result = this.fПрограммы;
                // *** Start programmer edit section *** (Сервер.Программы Get end)

                // *** End programmer edit section *** (Сервер.Программы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сервер.Программы Set start)

                // *** End programmer edit section *** (Сервер.Программы Set start)
                this.fПрограммы = value;
                // *** Start programmer edit section *** (Сервер.Программы Set end)

                // *** End programmer edit section *** (Сервер.Программы Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СерверE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СерверE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СерверE", typeof(IIS.ZxccxzxczxcxzXXX.Сервер));
                }
            }
            
            /// <summary>
            /// "СерверL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СерверL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СерверL", typeof(IIS.ZxccxzxczxcxzXXX.Сервер));
                }
            }
        }
    }
}
