//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.ZxccxzxczxcxzXXX
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тип настр.
    /// </summary>
    // *** Start programmer edit section *** (ТипНастр CustomAttributes)

    // *** End programmer edit section *** (ТипНастр CustomAttributes)
    public enum ТипНастр
    {
        
        // *** Start programmer edit section *** (ТипНастр.ВыборХост CustomAttributes)

        // *** End programmer edit section *** (ТипНастр.ВыборХост CustomAttributes)
        ВыборХост,
        
        // *** Start programmer edit section *** (ТипНастр.УстОС CustomAttributes)

        // *** End programmer edit section *** (ТипНастр.УстОС CustomAttributes)
        УстОС,
        
        // *** Start programmer edit section *** (ТипНастр.УстСервПО CustomAttributes)

        // *** End programmer edit section *** (ТипНастр.УстСервПО CustomAttributes)
        УстСервПО,
        
        // *** Start programmer edit section *** (ТипНастр.НастрСети CustomAttributes)

        // *** End programmer edit section *** (ТипНастр.НастрСети CustomAttributes)
        НастрСети,
    }
}
